# Site settings
title: Nick Mosher
email: nicholastmosher@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I'm a software engineering major at RIT and a member of Computer Science House!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://nicholastmosher.com" # the base hostname & protocol for your site
github_username:  nicholastmosher

# Build settings
markdown: kramdown
